[2023-01-26T15:39:11.986-0300] {processor.py:153} INFO - Started process (PID=127) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:11.987-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:39:11.988-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:39:11.988-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:12.352-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:39:12.345-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:39:12.353-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:12.382-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.398 seconds
[2023-01-26T15:39:43.452-0300] {processor.py:153} INFO - Started process (PID=132) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:43.453-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:39:43.454-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:39:43.454-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:43.608-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:39:43.604-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:39:43.608-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:39:43.632-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.182 seconds
[2023-01-26T15:40:14.107-0300] {processor.py:153} INFO - Started process (PID=133) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:14.108-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:40:14.109-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:40:14.109-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:14.262-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:40:14.258-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:40:14.263-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:14.300-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.194 seconds
[2023-01-26T15:40:44.710-0300] {processor.py:153} INFO - Started process (PID=134) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:44.711-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:40:44.711-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:40:44.711-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:44.862-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:40:44.859-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:40:44.863-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:40:44.902-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.194 seconds
[2023-01-26T15:41:15.384-0300] {processor.py:153} INFO - Started process (PID=135) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:15.385-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:41:15.385-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:41:15.385-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:15.575-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:41:15.570-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:41:15.576-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:15.619-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.238 seconds
[2023-01-26T15:41:45.986-0300] {processor.py:153} INFO - Started process (PID=136) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:45.987-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:41:45.987-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:41:45.987-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:46.140-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:41:46.135-0300] {dagbag.py:343} ERROR - Failed to import: /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/jucepos/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py", line 19, in <module>
    product_cat_name=pd.read_csv("datasets/product_category_name_translation.csv")
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/jucepos/.local/lib/python3.8/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/product_category_name_translation.csv'
[2023-01-26T15:41:46.140-0300] {processor.py:755} WARNING - No viable dags retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:41:46.179-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.194 seconds
[2023-01-26T15:42:17.206-0300] {processor.py:153} INFO - Started process (PID=137) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:17.207-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:42:17.207-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.207-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:17.363-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:17.468-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.467-0300] {manager.py:504} INFO - Created Permission View: can delete on DAG:first
[2023-01-26T15:42:17.497-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.497-0300] {manager.py:504} INFO - Created Permission View: can read on DAG:first
[2023-01-26T15:42:17.524-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.524-0300] {manager.py:504} INFO - Created Permission View: can edit on DAG:first
[2023-01-26T15:42:17.525-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.525-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:42:17.646-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.646-0300] {dag.py:2697} INFO - Creating ORM DAG for first
[2023-01-26T15:42:17.654-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:17.654-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:42:17.723-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.519 seconds
[2023-01-26T15:42:47.886-0300] {processor.py:153} INFO - Started process (PID=138) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:47.887-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:42:47.887-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:47.887-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:48.032-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:42:48.054-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:48.054-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:42:48.071-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:42:48.071-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:42:48.131-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.247 seconds
[2023-01-26T15:43:18.375-0300] {processor.py:153} INFO - Started process (PID=139) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:18.376-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:43:18.376-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:18.376-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:18.519-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:18.541-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:18.540-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:43:18.556-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:18.556-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:43:18.607-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.234 seconds
[2023-01-26T15:43:48.881-0300] {processor.py:153} INFO - Started process (PID=140) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:48.882-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:43:48.883-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:48.883-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:49.084-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:43:49.106-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:49.106-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:43:49.123-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:43:49.123-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:43:49.176-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.298 seconds
[2023-01-26T15:44:19.485-0300] {processor.py:153} INFO - Started process (PID=141) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:19.486-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:44:19.487-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:19.487-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:19.634-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:19.656-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:19.656-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:44:19.673-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:19.673-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:44:19.734-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.251 seconds
[2023-01-26T15:44:49.992-0300] {processor.py:153} INFO - Started process (PID=142) to work on /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:49.993-0300] {processor.py:743} INFO - Processing file /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py for tasks to queue
[2023-01-26T15:44:49.994-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:49.993-0300] {dagbag.py:538} INFO - Filling up the DagBag from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:50.148-0300] {processor.py:753} INFO - DAG(s) dict_keys(['first']) retrieved from /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py
[2023-01-26T15:44:50.170-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:50.169-0300] {dag.py:2676} INFO - Sync 1 DAGs
[2023-01-26T15:44:50.187-0300] {logging_mixin.py:137} INFO - [2023-01-26T15:44:50.187-0300] {dag.py:3423} INFO - Setting next_dagrun for first to 2023-01-24T03:00:00+00:00, run_after=2023-01-25T03:00:00+00:00
[2023-01-26T15:44:50.248-0300] {processor.py:175} INFO - Processing /mnt/c/Users/jpost/OneDrive/Escritorio/Final-Data/Proyecto-Final-DATA-1/airflow/dags/prueba.py took 0.259 seconds
